[[navbar]]
  identifier = "intro"
  name = "Intro"
  url = "/intro/"
  pre = "ğŸ“”"
  weight = 1
[[navbar]]
  identifier = "factbook"
  name = "Factbook"
  pre = "ğŸ““"
  url = "/factbook/"
  weight = 2
    [[navbar]]
    identifier = "map"
    name = "Map"
    pre = "ğŸ—ºï¸"
    url = "/factbook/map/"
    parent = "factbook"
    weight = 1
  [[navbar]]
    identifier = "vekllei"
    name = "Vekllei"
    pre = "ğŸŒ¹"
    url = "/factbook/vekllei/"
    parent = "factbook"
    weight = 2
  [[navbar]]
    identifier = "bulletin"
    name = "Bulletin"
    pre = "ğŸ§¾"
    url = "/factbook/bulletin/"
    parent = "factbook"
    weight = 3
  [[navbar]]
    identifier = "culture"
    name = "Culture"
    pre = "ğŸµ"
    url = "/factbook/society/culture"
    parent = "factbook"
    weight = 4
    [[navbar]]
      identifier = "language"
      name = "Language"
      pre = "ğŸ“–"
      url = "/factbook/society/culture/language"
      parent = "culture"
      weight = 1
    [[navbar]]
      identifier = "metaphysics"
      name = "Metaphysics"
      pre = "ğŸª¬"
      url = "/factbook/society/culture/metaphysics"
      parent = "culture"
      weight = 2
    [[navbar]]
      identifier = "religion"
      name = "Religion"
      pre = "ğŸ’€"
      url = "/factbook/society/culture/religion"
      parent = "culture"
      weight = 3
    [[navbar]]
      identifier = "sagas"
      name = "Sagas"
      pre = "ğŸ•¯ï¸"
      url = "/factbook/society/culture/sagas"
      parent = "culture"
      weight = 4
  [[navbar]]
    identifier = "landscape"
    name = "Landscape"
    pre = "ğŸŒ¿"
    parent = "factbook"
    url = "/factbook/landscape"
    weight = 5
    [[navbar]]
      identifier = "boroughs"
      name = "Boroughs"
      pre = "ğŸŒ"
      url = "/factbook/landscape/boroughs"
      parent = "landscape"
      weight = 1
  [[navbar]]
    identifier = "society"
    name = "Society"
    pre = "ğŸ›"
    parent = "factbook"
    url = "/factbook/society"
    weight = 6
    [[navbar]]
      identifier = "state"
      name = "State"
      pre = "ğŸŒ¸"
      url = "/factbook/society/state/"
      parent = "society"
      weight = 1
    [[navbar]]
      identifier = "industry"
      name = "Industry"
      pre = "âš™ï¸"
      url = "/factbook/society/industry/"
      parent = "society"
      weight = 2
    [[navbar]]
    identifier = "technology"
    name = "Technology"
    pre = "ğŸ§ª"
    url = "/factbook/society/technology"
    parent = "society"
    weight = 3
  [[navbar]]
    identifier = "timeline"
    name = "Timeline"
    pre = "â³"
    parent = "factbook"
    url = "/factbook/timeline"
    weight = 6
[[navbar]]
  identifier = "newsdesk"
  name = "MillMint"
  pre = "ğŸ“•"
  url = "/millmint/"
  weight = 3
  [[navbar]]
    identifier = "about"
    name = "About"
    pre = "ğŸŒ"
    url = "/millmint/about"
    parent = "newsdesk"
    weight = 1
  [[navbar]]
    identifier = "dolls"
    name = "Dolls"
    pre = "ğŸ§â€â™€ï¸"
    url = "/millmint/dolls/"
    parent = "newsdesk"
    weight = 2
  [[navbar]]
    identifier = "commissions"
    name = "Commissions"
    pre = "âœï¸"
    url = "/millmint/commissions"
    parent = "newsdesk"
    weight = 3
  [[navbar]]
    identifier = "essays"
    name = "Essays"
    pre = "ğŸ“„"
    url = "/millmint/essays"
    parent = "newsdesk"
    weight = 4
    [[navbar]]
      identifier = "social-economy"
      name = "A Social Economy"
      pre = "ğŸ’¸"
      url = "/millmint/essays/social-economy"
      parent = "essays"
      weight = 1
    [[navbar]]
      identifier = "ghibli"
      name = "A Universal Nostalgia"
      pre = "ğŸ«§"
      url = "/millmint/essays/ghibli"
      parent = "essays"
      weight = 2
    [[navbar]]
      identifier = "utopie"
      name = "Utopie Concrete"
      pre = "â˜•ï¸"
      url = "/millmint/essays/utopie"
      parent = "essays"
      weight = 3
    [[navbar]]
      identifier = "hong kong"
      name = "Not Long in Hong Kong"
      pre = "â˜‚ï¸"
      url = "/millmint/essays/hongkong"
      parent = "essays"
      weight = 4
    [[navbar]]
      identifier = "west"
      name = "The West Coast"
      pre = "ğŸ”ï¸"
      url = "/millmint/essays/west"
      parent = "essays"
      weight = 5
[[navbar]]
  identifier = "posts"
  name = "Stories"
  pre = "ğŸ“—"
  url = "/stories/"
  weight = 4